export const array = [{
    image: "dfff",
    title: "rcxcxcr",
    author: "rrdddxcxc",
    price: "eeexcxc",
    description: "rxcxcrdvcvvdd"
}, {
    image: "ddd",
    title: "rr",
    author: "rrddd",
    price: "eee",
    description: "rrdvcvvdd"
}, {
    image: "dfff",
    title: "rcxcxcr",
    author: "rrdddxcxc",
    price: "eeexcxc",
    description: "rxcxcrdvcvvdd"
}, {
    image: "ddd",
    title: "rr",
    author: "rrddd",
    price: "eee",
    description: "rrdvcvvdd"
},
    {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    },
    {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    },
    {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }, {
        image: "ddd",
        title: "rr",
        author: "rrddd",
        price: "eee",
        description: "rrdvcvvdd"
    }, {
        image: "dfff",
        title: "rcxcxcr",
        author: "rrdddxcxc",
        price: "eeexcxc",
        description: "rxcxcrdvcvvdd"
    }
];